baseURL = "https://leonardofaria.net/"
languageCode = "en-us"
title = "Peirong Liu"
theme = "bento"

googleAnalytics = "UA-157386-6"
disqusShortname = "leonardofaria"

[markup.highlight]
  style = "github"
[markup.goldmark.renderer]
  unsafe = true

[params]
  intro = true
  headline = "Hi, I'm Peirong 👋"
  description = "My name is Peirong Liu (刘沛榕), a 3rd year PhD student in Computer Science at UNC-Chapel Hill." 

  # favicon = "favicon.ico" # TODO: add support
  cover = "images/vancouver.jpg"
  #ogImage = "images/og_image.jpg"

  github = "leonardofaria"
  twitter = "leozera"
  linkedin = "https://linkedin.com/in/leonardofariacoelho"
  email = "peirong@cs.unc.edu"
  #rss = "/feed"
  #webmention = "leonardofaria.net"
  #productionBaseUrl = "https://leonardofaria.net"

  avatar = "images/me.jpg"

  #showAuthorBio = true
  #authorBio = "If you like my content, follow me on <a #class='transition duration-300 ease-in-out #hover:text-blue-600' #href='https://twitter.com/leozera'>Twitter</a> and <a #class='transition #duration-300 ease-in-out hover:text-blue-600' #href='https://github.com/leonardofaria'>GitHub</a>"


  [[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 1

  [[menu.main]]
    name = "Publications"
    url = "/publications"
    weight = 1

  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio"
    weight = 1

  [[menu.main]]
    name = "Talks"
    url = "/talks"
    weight = 1

# [params.fathomAnalytics]
#   siteID = "MBRIL"
#   # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#   serverURL = "ft.leonardofaria.net"

[params.umami]
  siteID = "ef25ee64-202b-4378-822f-22398533a59c"
  trackerScript = "https://umami.leonardofaria.net/umami.js"

#[permalinks]
#  posts = "/:year/:month/:day/:title/"

