baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 10

 

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "page" #post, page
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5 #2
  # Enable to show reading time in minutes for posts
  showReadingTime = false


[languages]
  [languages.en]
    title = "Peirong Liu" 
    #subtitle = "Peirong"
    keywords = ""
    copyright = ""
    #menuMore = "Show more"
    #writtenBy = "Written by"
    #readMore = "Read more"
    #readOtherPosts = "Read other posts"
    #newerPosts = "Newer posts"
    #olderPosts = "Older posts"
    #minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo] 
      logoText = "$ cd /home/peirong"
      logoHomeLink = "/about"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "1"
        name = "About"
        url = "/about" 

      [[languages.en.menu.main]]
        identifier = "2"
        name = "News"
        url = "/news" 
	
      [[languages.en.menu.main]]
        identifier = "3"
        name = "Post"
        url = "/post" 

      [[languages.en.menu.main]]
        identifier = "5"
        name = "Resume/CV"
        url = "/cv_peirong.pdf" 
